server:
  port: 8090
spring:
  profiles:
    active:
      - "qa"
  application:
    name: loans
  jpa:
    show-sql: true
  management:
   tracing:
    sampling:
      probability: 1.0

  logging:
   pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  info:
    env:
      enabled: true
  config:
    import:
      optional:
       config server: http://localhost:8071
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  message: "welcome to loan application default profile"
  name: "raj default profile"
