#spring.main.allow-bean-definition-overriding=true
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
spring:
  zipkin:
   baseUrl: http://localhost:9411/

  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - "qa"
  application:
    name: accounts
  jpa:
    show-sql: true

  management:

   tracing:
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

   logging:
   pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


    exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  info:
    env:
      enabled: true

  config:
    import:
     optional:
     config server: http://localhost:8071

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  message: "welcome to accounts application default profile"
  name: "raj default profile accounts"


